### ISSUE TITLE
Reverse engineer changeset from exiting hiera configs?

### ISSUE THREAD

**Issue by jewzaam** [alechenninger/monarch#14]
Already have a ton of stuff in hiera for a project, would be great to generate the changeset from that as a starting point.  And maybe an example for how to cleanup duplicate keys by generate a changeset then generate the hiera data from the changeset.

**Comment by alechenninger** [comment]
Not sure I quite understand the use case. A changeset doesn't need to be comprehensive, it'll work from the current state of your hieradata. So if you have a data source like:

foo.yaml:

``` yaml
foo: 'bar'
baz: 123
```

And a change like:

``` yaml
---
  source: foo.yaml
  set:
    fizz: 'buzz'
```

The result data source will look like

``` yaml
foo: 'bar'
baz: 123
fizz: 'buzz'
```

In other words, existing keys that are not mentioned in changeset are not touched. Does this address your use case?

Thanks!
