### ISSUE TITLE
Config file expects values to be strings; does not like arbitrary yaml

### ISSUE THREAD

**Issue by alechenninger** [alechenninger/monarch#20]
This should work:

``` yaml
hierarchy:
  foo:
    - bar
    - baz
mergeKeys:
  - key1
  - key2
```

Right now this only works if you indicate the hierarchy and mergeKey values are strings (using >)
