### ISSUE TITLE
Support hierarchy defined with variables instead of static path tree

### ISSUE THREAD

**Issue by alechenninger** [alechenninger/monarch#53]
Essentially, like hiera proper:

``` yaml

---
:hierarchy:
  - "nodes/%{trusted.certname}"
  - "environment/%{server_facts.environment}"
  - "virtual/%{::is_virtual}"
  - common
```

So in a change:

``` yaml
# when no source: ... try facts instead
facts:
  trusted.certname: fake.com
  server_facts.environment: production
  ::is_virtual: true
set:
  etc: values here
```
