### ISSUE TITLE
Variables in a change set

### ISSUE THREAD

**Issue by alechenninger** [alechenninger/monarch#6]
Would maybe be convenient to do something like 

``` yaml

---
  source: foo
  variables:
    version: 1.2.3
  set:
    myapp1::version: ${version}
    myapp2::version: ${version}
    myapp3::version: ${version}
```

But maybe not
