### ISSUE TITLE
NPE when potentials for variable has nulls

### ISSUE THREAD

**Issue by alechenninger** [alechenninger/monarch#66]
I think this happens when:

``` yaml
hierarchy:
  sources:
    - %{foo}.yaml
  potentials:
    foo:
      -
```
