### ISSUE TITLE
Allow one variable definition to define others, implicitly

### ISSUE THREAD

**Issue by alechenninger** [alechenninger/monarch#67]
For example, imagine a dynamic hierarchy like this:

``` yaml
hierarchy:
  sources:
    - common.yaml
    - environment/%{environment}.yaml
    - team/%{team}.yaml
    - team/%{team}/%{environment}.yaml
    - node/%{hostname}.yaml
  potentials:
    # snip...
    hostname:
      - myhost.prod.mycompany.com:
        environment: prod
        team: myteam
```

Then, if you defined a target by `hostname=myhost.prod.mycompany.com`, you would have a complete hierarchy, without having to manually define environment and team for that node too, which you already know statically in advance.

Additionally, the reverse is true. If you targeted `environment=prod` or `team=myteam`, you would know that host was a descendant.
